### ISSUE TITLE
Release libserialport 0.1.2 on Github

### ISSUE THREAD

**Issue by MCUdude** [sigrokproject/libserialport#18]
Hi @abraxa! I'm very happy to see a new libserialport release! Would you mind dong a "release" on github as well, so package managers like [brew](https://brew.sh) can pick it up automatically? Thanks! 🚀

**Comment by abraxa** [comment]
Hi, will do, I'm not quite finished just yet. Need to still finish up and create a tagged branch but I'll do that as soon as time permits. Thanks for your hint!
